// Auto-generated by scripts/generate-payment-config.mjs
// Field reference: skills/payment-web-builder/references/payment-method-selector-config.md
// The `target` field is optional — leave empty to use the processor's default merchant account.

export const PAYMENT_METHOD_CONFIG = [
    {
        paymentMethod: 'CreditCard',
        paymentProcessor: 'AuthorizeNet-for-FinDock',
        target: '',
        enabledOneTime: true,
        enabledRecurring: true,
        isDefaultOneTime: true,
        isDefaultRecurring: true,
        supportsRecurring: true,
        displayLabel: 'CreditCard',
        parameters: [
            {
                name: 'description',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'description',
                required: false,
                data_type: 'String',
                description: 'Description of the payment for the payer’s bank.'
            },
            {
                name: 'countryCode',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'countryCode',
                required: false,
                data_type: 'String',
                description: 'Two-letter country code. Examples: NL, US.'
            }
        ]
    },
    {
        paymentMethod: 'CreditCard',
        paymentProcessor: 'PaymentHub-Stripe',
        target: 'My Stripe Account (New)',
        enabledOneTime: true,
        enabledRecurring: true,
        isDefaultOneTime: false,
        isDefaultRecurring: false,
        supportsRecurring: true,
        displayLabel: 'CreditCard',
        parameters: [
            {
                name: 'locale',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'locale',
                required: false,
                data_type: 'String',
                description: 'Expected input: language tags as outlined on https://www.oracle.com/java/technologies/javase/jdk13locales.html. Examples: nl-NL, en-US.'
            },
            {
                name: 'itemName',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'itemName',
                required: false,
                data_type: 'String',
                description: 'The name for the item to be displayed on the hosted payment / checkout page.'
            },
            {
                name: 'description',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'description',
                required: false,
                data_type: 'String',
                description: 'Description of the payment for the payer’s bank.'
            }
        ]
    },
    {
        paymentMethod: 'ACH Direct Debit',
        paymentProcessor: 'AuthorizeNet-for-FinDock',
        // TODO: fill in target — FinDock Setup → Processors & Methods → AuthorizeNet-for-FinDock → Accounts tab
        target: '',
        enabledOneTime: false,
        enabledRecurring: true,
        isDefaultOneTime: false,
        isDefaultRecurring: false,
        supportsRecurring: true,
        displayLabel: 'ACH Direct Debit',
        parameters: [
            {
                name: 'description',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'description',
                required: false,
                data_type: 'String',
                description: 'Description of the payment for the payer’s bank.'
            }
        ]
    },
    {
        paymentMethod: 'ACH Direct Debit',
        paymentProcessor: 'PaymentHub-Stripe',
        target: 'My Stripe Account (New)',
        enabledOneTime: false,
        enabledRecurring: false,
        isDefaultOneTime: false,
        isDefaultRecurring: false,
        supportsRecurring: true,
        displayLabel: 'ACH Direct Debit',
        parameters: [
            {
                name: 'locale',
                value: 'nl-NL',
                visibleToCustomer: false,
                displayLabel: 'locale',
                required: false,
                data_type: 'String',
                description: 'Expected input: language tags as outlined on https://www.oracle.com/java/technologies/javase/jdk13locales.html. Examples: nl-NL, en-US.'
            },
            {
                name: 'itemName',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'itemName',
                required: false,
                data_type: 'String',
                description: 'The name for the item to be displayed on the hosted payment / checkout page.'
            },
            {
                name: 'description',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'description',
                required: false,
                data_type: 'String',
                description: 'Description of the payment for the payer’s bank.'
            }
        ]
    },
    {
        paymentMethod: 'Ideal',
        paymentProcessor: 'PaymentHub-Stripe',
        target: 'My Stripe Account (New)',
        enabledOneTime: true,
        enabledRecurring: false,
        isDefaultOneTime: false,
        isDefaultRecurring: false,
        supportsRecurring: false,
        displayLabel: 'Ideal',
        parameters: [
            {
                name: 'locale',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'locale',
                required: false,
                data_type: 'String',
                description: 'Expected input: language tags as outlined on https://www.oracle.com/java/technologies/javase/jdk13locales.html. Examples: nl-NL, en-US.'
            },
            {
                name: 'itemName',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'itemName',
                required: false,
                data_type: 'String',
                description: 'The name for the item to be displayed on the hosted payment / checkout page.'
            }
        ]
    },
    {
        paymentMethod: 'Bancontact',
        paymentProcessor: 'PaymentHub-Stripe',
        target: 'My Stripe Account (New)',
        enabledOneTime: true,
        enabledRecurring: false,
        isDefaultOneTime: false,
        isDefaultRecurring: false,
        supportsRecurring: false,
        displayLabel: 'Bancontact',
        parameters: [
            {
                name: 'locale',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'locale',
                required: false,
                data_type: 'String',
                description: 'Expected input: language tags as outlined on https://www.oracle.com/java/technologies/javase/jdk13locales.html. Examples: nl-NL, en-US.'
            },
            {
                name: 'itemName',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'itemName',
                required: false,
                data_type: 'String',
                description: 'The name for the item to be displayed on the hosted payment / checkout page.'
            }
        ]
    },
    {
        paymentMethod: 'SEPA Direct Debit',
        paymentProcessor: 'PaymentHub-Stripe',
        target: 'My Stripe Account (New)',
        enabledOneTime: true,
        enabledRecurring: true,
        isDefaultOneTime: false,
        isDefaultRecurring: false,
        supportsRecurring: true,
        displayLabel: 'SEPA Direct Debit',
        parameters: [
            {
                name: 'locale',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'locale',
                required: false,
                data_type: 'String',
                description: 'Expected input: language tags as outlined on https://www.oracle.com/java/technologies/javase/jdk13locales.html. Examples: nl-NL, en-US.'
            },
            {
                name: 'itemName',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'itemName',
                required: false,
                data_type: 'String',
                description: 'The name for the item to be displayed on the hosted payment / checkout page.'
            },
            {
                name: 'description',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'description',
                required: false,
                data_type: 'String',
                description: 'Description of the payment for the payer’s bank.'
            }
        ]
    },
    {
        paymentMethod: 'BACS Direct Debit',
        paymentProcessor: 'PaymentHub-Stripe',
        target: 'My Stripe Account (New)',
        enabledOneTime: true,
        enabledRecurring: true,
        isDefaultOneTime: false,
        isDefaultRecurring: false,
        supportsRecurring: true,
        displayLabel: 'BACS Direct Debit',
        parameters: [
            {
                name: 'locale',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'locale',
                required: false,
                data_type: 'String',
                description: 'Expected input: language tags as outlined on https://www.oracle.com/java/technologies/javase/jdk13locales.html. Examples: nl-NL, en-US.'
            },
            {
                name: 'itemName',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'itemName',
                required: false,
                data_type: 'String',
                description: 'The name for the item to be displayed on the hosted payment / checkout page.'
            },
            {
                name: 'description',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'description',
                required: false,
                data_type: 'String',
                description: 'Description of the payment for the payer’s bank.'
            }
        ]
    },
    {
        paymentMethod: 'Przelewy24',
        paymentProcessor: 'PaymentHub-Stripe',
        target: '',
        enabledOneTime: true,
        enabledRecurring: false,
        isDefaultOneTime: false,
        isDefaultRecurring: false,
        supportsRecurring: false,
        displayLabel: 'Przelewy24',
        parameters: [
            {
                name: 'locale',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'locale',
                required: false,
                data_type: 'String',
                description: 'Expected input: language tags as outlined on https://www.oracle.com/java/technologies/javase/jdk13locales.html. Examples: nl-NL, en-US.'
            },
            {
                name: 'itemName',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'itemName',
                required: false,
                data_type: 'String',
                description: 'The name for the item to be displayed on the hosted payment / checkout page.'
            },
            {
                name: 'description',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'description',
                required: false,
                data_type: 'String',
                description: 'Description of the payment for the payer’s bank.'
            }
        ]
    },
    {
        paymentMethod: 'BLIK',
        paymentProcessor: 'PaymentHub-Stripe',
        target: 'My Stripe Account (New)',
        enabledOneTime: true,
        enabledRecurring: false,
        isDefaultOneTime: false,
        isDefaultRecurring: false,
        supportsRecurring: false,
        displayLabel: 'BLIK',
        parameters: [
            {
                name: 'locale',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'locale',
                required: false,
                data_type: 'String',
                description: 'Expected input: language tags as outlined on https://www.oracle.com/java/technologies/javase/jdk13locales.html. Examples: nl-NL, en-US.'
            },
            {
                name: 'itemName',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'itemName',
                required: false,
                data_type: 'String',
                description: 'The name for the item to be displayed on the hosted payment / checkout page.'
            },
            {
                name: 'description',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'description',
                required: false,
                data_type: 'String',
                description: 'Description of the payment for the payer’s bank.'
            }
        ]
    },
    {
        paymentMethod: 'PAD',
        paymentProcessor: 'PaymentHub-Stripe',
        target: 'My Stripe Account (New)',
        enabledOneTime: true,
        enabledRecurring: true,
        isDefaultOneTime: false,
        isDefaultRecurring: false,
        supportsRecurring: true,
        displayLabel: 'PAD',
        parameters: [
            {
                name: 'locale',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'locale',
                required: false,
                data_type: 'String',
                description: 'Expected input: language tags as outlined on https://www.oracle.com/java/technologies/javase/jdk13locales.html. Examples: nl-NL, en-US.'
            },
            {
                name: 'itemName',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'itemName',
                required: false,
                data_type: 'String',
                description: 'The name for the item to be displayed on the hosted payment / checkout page.'
            },
            {
                name: 'description',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'description',
                required: false,
                data_type: 'String',
                description: 'Description of the payment for the payer’s bank.'
            }
        ]
    },
    {
        paymentMethod: 'Satispay',
        paymentProcessor: 'PaymentHub-Stripe',
        target: 'My Stripe Account (New)',
        enabledOneTime: true,
        enabledRecurring: true,
        isDefaultOneTime: false,
        isDefaultRecurring: false,
        supportsRecurring: true,
        displayLabel: 'Satispay',
        parameters: [
            {
                name: 'locale',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'locale',
                required: false,
                data_type: 'String',
                description: 'Expected input: language tags as outlined on https://www.oracle.com/java/technologies/javase/jdk13locales.html. Examples: nl-NL, en-US.'
            },
            {
                name: 'itemName',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'itemName',
                required: false,
                data_type: 'String',
                description: 'The name for the item to be displayed on the hosted payment / checkout page.'
            },
            {
                name: 'description',
                value: '',
                visibleToCustomer: false,
                displayLabel: 'description',
                required: false,
                data_type: 'String',
                description: 'Description of the payment for the payer’s bank.'
            }
        ]
    }
];
